SELECT
    ordersnom.id,
    ordersnom.name,
    ordersnom.description,
    ordersnom.kolvo,
    ordersnom.kolvo_add,
    ordersnom.mats_from,
    dbo.zag_info_full('nom',ordersnom.nom_id,kolvo_add) AS zag_nom,
    dbo.zag_info_full('tech',ordersnom.id,kolvo_add) AS zag_tech,
    CASE WHEN ordersnom.p_price_det = 0 THEN dbo.p_price_det_orders(ordersnom.id) ELSE ordersnom.p_price_det END AS p_price_det,
    dbo.p_info_orders(ordersnom.id),
    ordersnom.pokr_maker,
    ordersnom.pokr_area,
    mats.profile,
    mats."group" material,
    mats.name mat_name,
    ordersnom.zag_type,
    ordersnom.zag_tech_material_id,
    ordersnom.zag_tech_p1,
    ordersnom.zag_tech_p2,
    ordersnom.zag_tech_p3,
    ordersnom.zag_tech_p4,
    ordersnom.zag_tech_density,
    zag_buy_material_id,
    zag_buy_p1,
    zag_buy_p2,
    zag_buy_p3,
    zag_buy_p4,
    ordersnom.zag_tech_density,
    zag_buy_weight,
    metall_price_kg,
    metall_price_total_det,
    metall_price_add,
    metall_buy_time,
    ordersnom.zag_tech_kolvo_det,
    ordersnom.zag_comments,
    dbo.logistics_price_kg(ordersnom.order_id),
    dbo.nom.fio tech_fio,
    dbo.nom.tech_id,
    ordersnom.comments,
    ordersnom.norma,
    ordersnom.instr_info,
    ordersnom.cal_price_det,
    ordersnom.instr_price_det,
    ordersnom.term_price_det,
    ordersnom.outsource_price_det,
    FALSE AS recalc
FROM dbo.ordersnom
    INNER JOIN dbo.mats ON mats.id = ordersnom.zag_tech_material_id
    INNER JOIN dbo.nom ON nom.id = ordersnom.nom_id
WHERE ordersnom.id = :orders_nom_id
